---
title: "Data completeness state"
author: "Dan Weinberger"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ExcessILI)
library(cdcfluview)
library(reshape2)
library(ggplot2)
library(lubridate)
library(RColorBrewer)
library(plotly)
library(MMWRweek)
library(readr)
library(rjson)
library(htmlTable)
library(RSocrata)
library(pdftools)
library(readr)
library(gsubfn)
library(INLA)
library (RCurl)


```
## Backfilling

```{r}
#Data from Andrew:NOTE: it looks like July-oct 2019 is missing from these data
wk11 <- 
  read.csv('./archives_do_not_sync/State_Custom_Data11.csv')
wk11$max.date.report <- as.Date('2020-03-14')
wk11$report.date <- as.Date('2020-03-27')

wk12 <- 
  read.csv('./archives_do_not_sync/State_Custom_Data12.csv')
wk12$max.date.report <- as.Date('2020-03-21')
wk12$report.date <- as.Date('2020-04-03')

wk13 <- 
  read.csv('./archives_do_not_sync/State_Custom_Data13.csv')
wk13$max.date.report <- as.Date('2020-03-28')
wk13$report.date <- as.Date('2020-04-10')

wk15 <- 
  read.csv('./archives_do_not_sync/State_Custom_Data15.csv')
wk15$max.date.report <- as.Date('2020-04-11')
wk15$report.date <- as.Date('2020-04-17')

wk16 <- 
  read.csv('./archives_do_not_sync/State_Custom_Data16.csv')
wk16$max.date.report <- as.Date('2020-04-18')
wk16$report.date <- as.Date('2020-04-24')

wk17 <- 
  read.csv('./archives_do_not_sync/State_Custom_Data17.csv')
wk17$max.date.report <- as.Date('2020-04-25')
wk17$report.date <- as.Date('2020-05-01')


all.reports <- rbind.data.frame(wk11,wk12,wk13,wk15, wk16, wk17)


all.reports$epiyr <-
  as.numeric(as.character(substr(all.reports$SEASON,1,4)))

all.reports$year <- all.reports$epiyr
all.reports$year[all.reports$WEEK<=26] <-
  all.reports$epiyr[all.reports$WEEK<=26] +1
all.reports$week.death <-
  mmwr_week_to_date(all.reports$year, all.reports$WEEK)+6

#Fix formatting for the count variables
all.reports$NUM.INFLUENZA.DEATHS <-
  gsub(',','',all.reports$NUM.INFLUENZA.DEATHS) 
all.reports$NUM.INFLUENZA.DEATHS <-  as.numeric(as.character(all.reports$NUM.INFLUENZA.DEATHS)) 

all.reports$NUM.PNEUMONIA.DEATHS <-
  gsub(',','',all.reports$NUM.PNEUMONIA.DEATHS) 
all.reports$NUM.PNEUMONIA.DEATHS <-  as.numeric(as.character(all.reports$NUM.PNEUMONIA.DEATHS)) 

all.reports$TOTAL.DEATHS <-
  gsub(',','',all.reports$TOTAL.DEATHS) 
all.reports$TOTAL.DEATHS <-  as.numeric(as.character(all.reports$TOTAL.DEATHS))

compare.m <- melt(all.reports[,c("week.death","SUB.AREA" ,"report.date","TOTAL.DEATHS" )], id.vars  =c("week.death",'SUB.AREA',"report.date"))

names(compare.m) <- 
  c('death_date','state','report_date','variable','N_deaths')

compare.m$report_date <-as.Date(compare.m$report_date)
compare.m$death_date <-as.Date(compare.m$death_date)

compare.m$complete.weeks <- round(as.vector(difftime(compare.m$report_date,
          compare.m$death_date, units='weeks')))
#compare.m$complete.weeks[compare.m$complete.weeks>5] <-5

compare.c <- dcast( compare.m[,c('death_date','state','report_date','N_deaths')], state+ death_date ~ report_date, value.var='N_deaths', fun.aggregate = mean)


new.reports <- compare.c
new.reports[,-c(1:2)] <- 
  apply(new.reports[,-c(1:2)],2, function(x){ 
    x[is.nan(x)] <- 0 
    return(x)
  
  })
new.reports2 <- new.reports
# count new reports
# for(i in 2:4){
# new.reports2[,(2+i)]  <-
#   new.reports[,(2+i)] - new.reports[,(2+i-1 )]
# }

new.reports2.m <- 
  melt(new.reports2, id.vars=c('state', 'death_date'))

names(new.reports2.m) <- c('state','death_date', 'report_date','N_new_reports')

new.reports2.m$death_date <- 
  as.Date( new.reports2.m$death_date)

new.reports2.m$report_date <- 
  as.Date( new.reports2.m$report_date)

new.reports2.m$time.report <-
  round(as.numeric(difftime(new.reports2.m$report_date,
     new.reports2.m$death_date,units='weeks') ))

new.reports2.m$time.report[new.reports2.m$time.report>=8] <- 8

new.reports2.m$time.report <-
  as.numeric(as.character(new.reports2.m$time.report))

#filter observations when report date is before death date
new.reports2.m <-
  new.reports2.m[(new.reports2.m$time.report > 0 & new.reports2.m$report_date>=as.Date('2020-04-11')) | (new.reports2.m$time.report > 1 & new.reports2.m$report_date<as.Date('2020-04-11')) 
                   ,] 

new.reports2.m <-
  new.reports2.m[new.reports2.m$time.report>0,] 

new.reports2.m$N_new_reports[new.reports2.m$N_new_reports<0] <- 0
```

Now setup a model
```{r, fig.width=12, fig.height=12}
compare.m1 <- new.reports2.m

# for recent dates,
date.fill1 <- unique(compare.m1[,c('death_date','time.report' ,'state')])
date.fill1.spl <- split(date.fill1,
                       paste( date.fill1$death_date,
                              date.fill1$state))

date.fill1.spl <- lapply(date.fill1.spl, function(x){
  x$time.report <-
    as.numeric(as.character(x$time.report))
  
  max.time.date <- 
    max( x$time.report, na.rm=T)
  state1 <-unique(x$state)
  min.time.date <- 
    min( x$time.report, na.rm=T)
  
  if(max.time.date < 8){
    time.report2<-seq(from=min.time.date, to=8)
    date.rep <- rep(x$death_date, length(time.report2))
    date.time1 <-
      cbind.data.frame('time.report'=time.report2,
                       'death_date'= date.rep)
    x <- merge(x, date.time1, 
               by=c('death_date', 'time.report'), all=T)
    x$state <- state1
    }
  return(x)
})

date.fill2 <- do.call('rbind.data.frame', date.fill1.spl)
date.fill2 <- unique(date.fill2)

compare.m <- merge(compare.m1, date.fill2,
                   by=c('death_date', 
                        'time.report', 'state'),
                   all=T)

compare.m$time.report <- 
  as.factor(compare.m$time.report)

compare.m$time.report <-
  relevel(compare.m$time.report,'8')

compare.m$t2 <- 
  as.numeric(difftime(compare.m$death_date,
               min(compare.m$death_date),
               units='weeks'))
compare.m$sin52= sin(2*pi*compare.m$t2/52.1775)
compare.m$cos52= cos(2*pi*compare.m$t2/52.1775)
compare.m$sin26= sin(2*pi*compare.m$t2*2/52.1775)
compare.m$cos26= cos(2*pi*compare.m$t2*2/52.1775)
year1 <- year(compare.m$death_date)
month1 <- month(compare.m$death_date)
compare.m$epiyr <- year1
compare.m$epiyr[month1 <=6] <- year1[month1 <=6]-1
compare.m$epiyr <-as.factor(compare.m$epiyr)
```


```{r, fig.width=12, fig.height=12}
inla.func <- function(state.select){
  ny1 <- compare.m[compare.m$state ==state.select ,]
  ny1 <- ny1[!is.na(ny1$death_date),]
  ny1$death_date.fac <- as.factor(ny1$death_date)
  time.dummies <- model.matrix(~ time.report, data=ny1)
  ny1 <- cbind.data.frame(ny1, time.dummies[,-1])
  ny1$death_date.fac2 <- ny1$death_date.fac
  form1 <- 
    as.formula("N_new_reports ~ sin52 + cos52 +sin26 + cos26 + epiyr + time.report1 +time.report2 +time.report3 +time.report4 + time.report5 + time.report6 + time.report7 + f(death_date.fac, model='ar1')")
  dat.inla <- inla(form1, family='poisson',
     data=ny1,
     control.family=list(link='log'),
     control.predictor=list(link=1, compute=TRUE),
     control.compute=list(dic=TRUE, cpo=TRUE, waic=TRUE))
              #examine the regular summary 
 # summary(dat.inla)
  
fixed.effect <- dat.inla$summary.fixed[,c('sd','0.025quant','0.5quant','0.975quant')]
  results1<-list('input.data'=ny1,'dat.inla'=dat.inla,'fixed.effect'=fixed.effect )
return(results1)
}

states.test <- c('Alabama','Arizona','Arkansas','Colorado', 'District of Columbia', 'Florida','Georgia','Idaho','Illinois','Indiana','Kansas','Kentucky', 'Louisiana', 'Maryland','Massachusetts', 'Michigan','Minnesota','Montana','Nevada','New Jersey', 'New York', 'New York City', 'Oregon','Pennsylvania','South Carolina','Virginia','Utah', 'Texas', 'Washington')

all.state.mods <-
  lapply(states.test,inla.func )
```

```{r rr_fill_plot, fig.width=8, fig.height=8}
#plot the RR
plot.func.inla.rr <- function(inla.ds){
  dat.inla <- inla.ds$dat.inla
  ny1 <- inla.ds$input.data
  state.select <- unique(ny1$state)
  rand <-
    cbind.data.frame('death_date'=unique(ny1$death_date),dat.inla$summary.random)
  
  pred.combined <- cbind.data.frame(dat.inla$summary.fitted.values, ny1)
  
  pred.combined <- pred.combined[order(pred.combined$state, pred.combined$death_date),]
  
  pred.combined %>% tidyr::fill('N_new_reports')
  
  pred.sub <-pred.combined[pred.combined$death_date >= as.Date('2020-01-01') & pred.combined$time.report=='5' ,]
  y.range1 <- range(c(pred.sub$`0.975quant`, pred.sub$`0.025quant`, 0))
  # plot(pred.sub$death_date , pred.sub$mean,ylim=y.range1, col='white', main=state.select, bty='l')
  #  polygon(c(pred.sub$death_date,
  #             rev(pred.sub$death_date)),
  #           c(pred.sub$`0.025quant`,
  #             rev(pred.sub$`0.975quant`)),
  #             col = rgb(1, 0, 0, alpha = 0.1),
  #           border = NA
  #             )
  #  points(pred.sub$death_date,pred.sub$N_new_reports)
  
  rand2 <- rand[rand$death_date>=as.Date('2020-01-01'),]  
  y.range1 <- range(exp(c(rand2$death_date.fac.0.025quant, rand2$death_date.fac.0.975quant)))

   plot(rand2$death_date , 
        exp(rand2$death_date.fac.0.5quant),
        ylim=c(0.8, 3), lty=1,col='red',type='l',
        main=state.select, bty='l',
        ylab='Rate ratio all-cause deaths')
    polygon(c(rand2$death_date,
               rev(rand2$death_date)),
             exp(c(rand2$death_date.fac.0.025quant,
               rev(rand2$death_date.fac.0.975quant))),
               col = rgb(1, 0, 0, alpha = 0.1),
             border = NA
               )
    abline(h=1, lty=2, col='gray')
    abline(v=as.Date('2020-04-03'), lty=3, col='gray')
}

par(mfrow=c(4,4), mar=c(2,4,1,1))
lapply(all.state.mods, plot.func.inla.rr)

```

#predict inla
```{r}
linear.pred <- sapply(all.state.mods, function(x){
  y <- x$dat.inla$"summary.linear.predictor"$'0.5quant'
  return(y)
}, simplify='array')

plot(exp(linear.pred[,1]))

```


```{r fitted_fill_plot}
#plot the RR
plot.func.inla.obs.exp <- function(inla.ds){
  dat.inla <- inla.ds$dat.inla
  ny1 <- inla.ds$input.data
  state.select <- unique(ny1$state)
  rand <-
    cbind.data.frame('death_date'=unique(ny1$death_date),dat.inla$summary.random)
  
  pred.combined <- cbind.data.frame(dat.inla$summary.fitted.values, ny1)
  
  pred.combined <- pred.combined[order(pred.combined$state, pred.combined$death_date),]
  
  pred.combined %>% tidyr::fill('N_new_reports')
  
  pred.sub <-pred.combined[pred.combined$death_date >= as.Date('2020-01-01') & pred.combined$time.report=='5' ,]
  y.range1 <- range(c(pred.sub$`0.975quant`, pred.sub$`0.025quant`, 0))
  plot(pred.sub$death_date , pred.sub$mean,ylim=y.range1, col='white', main=state.select, bty='l')
   polygon(c(pred.sub$death_date,
              rev(pred.sub$death_date)),
            c(pred.sub$`0.025quant`,
              rev(pred.sub$`0.975quant`)),
              col = rgb(1, 0, 0, alpha = 0.1),
            border = NA
              )
   points(pred.sub$death_date,pred.sub$N_new_reports)
  
     abline(v=as.Date('2020-04-03'), lty=3, col='gray')
}

par(mfrow=c(4,5), mar=c(2,4,1,1))
lapply(all.state.mods, plot.func.inla.rr)

```

reporting delay by state and weeks since death
```{r, fig.width=5, fig.height=5}
fe.inla <- sapply(all.state.mods, function(x)  x$fixed.effect[c('time.report1','time.report2','time.report3','time.report4'),c('0.5quant')])
dimnames(fe.inla)[[2]] <- states.test

fe.inla.sd <- sapply(all.state.mods, function(x)  x$fixed.effect[c('time.report1','time.report2','time.report3','time.report4'),c('sd')])
dimnames(fe.inla.sd)[[2]] <- states.test

write.csv(exp(fe.inla),'./outputs/report.proportion.state.csv')
write.csv(fe.inla.sd,'./outputs/report.proportion.state.SD.csv')


matplot(round(100*exp(fe.inla)), type='l', bty='l', ylab='Percent complete', xlab='Weeks since death')
abline(h=1)
```



simple glm
```{r}
library(lme4)
glmer.func <- function(state.select){
  ny1 <- compare.m[compare.m$state ==state.select ,]
  ny1 <- ny1[!is.na(ny1$death_date),]
  ny1$death_date.fac <- as.factor(ny1$death_date)
  time.dummies <- model.matrix(~ time.report, data=ny1)
  ny1 <- cbind.data.frame(ny1, time.dummies[,-1])
  
  form1 <- 
    as.formula("N_new_reports ~ sin52 + cos52 +sin26 + cos26 + epiyr + time.report1 +time.report2 +time.report3 +time.report4 + time.report5 +time.report6 +time.report7 + (1|death_date.fac)")
  mod1 <- glmer(form1, family='poisson',
     data=ny1)
              #examine the regular summary 
 # summary(dat.inla)
  results1<-list('input.data'=ny1,'mod1'=mod1 )
return(results1)
}

states.test <- c('Alabama','Arizona','Florida','Georgia','Kentucky', 'Louisiana', 'Maryland','Massachusetts', 'Michigan','Minnesota','New Jersey', 'New York', 'New York City', 'Oregon','Pennsylvania','South Carolina','Virginia','Utah', 'Washington')

glmer.mods <- lapply(states.test, glmer.func)

fix.effs<-as.data.frame(sapply(glmer.mods, function(x) fixef(x$mod1)))
names(fix.effs) <- states.test
fix.effs <- fix.effs[c('time.report1','time.report2','time.report3','time.report4','time.report5','time.report6','time.report7'),]
```

Underreporting by state
```{r, fig.width=5, fig.height=5}
#If values close to 1, this indicates the value is closer to the final value. the comparison is to 5+ weeks out 
matplot(exp(fix.effs), type='l', xlab='Weeks since death', bty='l', ylab='estimate reporting proportion')
abline(h=1, lty=2, col='gray')
```

#Compare inla and glm
```{r}
plot( fe.inla, as.matrix(fix.effs))
```

## Scrape old data from NCHS
```{r, eval=F}

week.pad <-sprintf("%02d", c(1:52))
for(i in week.pad){
 #for( j in c('2019-2020','2018-2019','2017-2018','2016-2017')){
j='2019-2020'
  download.file(paste0('https://www.cdc.gov/flu/weekly/weeklyarchives', j,'/data/NCHSData',i,'.csv'),paste0('./Data/provisional_pi/provisional', j,'_','week_',i,'.csv'))
  }
}
```

```{r}
week.test <- '17' #week for which CDCfluview is for

provis.list <- lapply(c('2019-2020','2018-2019','2017-2018','2016-2017'),
                      function(x){
  d1 <- read.csv(paste0('./Data/provisional_pi/provisional', x,'_','week_',week.test,'.csv'))
  d1$provision.week <- week.test
  d1$provision.year<-x
  return(d1)
                        }
)

provis.data <- do.call('rbind.data.frame', provis.list)
provis.data$epiwk <- NA

provis.data$epiwk[provis.data$Week<=26] <-
  provis.data$Week[provis.data$Week<=26]+26

provis.data$epiwk[provis.data$Week>=27] <-
  provis.data$Week[provis.data$Week>=27]-26

provis.data$epiyr <- provis.data$Year

provis.data$epiyr[provis.data$Week<=26] <-
  provis.data$Year[provis.data$Week<=26] -1

#keep only year that has provisional data
provis.data <- 
  provis.data[as.character(provis.data$epiyr) ==
              substr(provis.data$provision.year,1,4),]

provis.data$pi.deaths <- provis.data$Pneumonia.Deaths +
  provis.data$Influenza.Deaths

provis.data.m <-  
  melt(provis.data[,c("All.Deaths",'pi.deaths','epiwk','Week','provision.year')],
       id.vars=c('epiwk','Week','provision.year'))

provis.data.c1 <- 
  dcast(provis.data.m, variable+epiwk+Week~provision.year)

provis.data.c1 <- 
  provis.data.c1[order(provis.data.c1$variable, provis.data.c1$epiwk),]

write.csv(provis.data.c1, './outputs/provisional_deaths_reported_in_wk15.csv')

provis.data.c <-
  provis.data.c1[complete.cases(provis.data.c1),]
```

```{r, fig.width=5, fig.height=4}
all.deaths.provis <-
  provis.data.c[provis.data.c$variable=='All.Deaths',]

all.deaths.provis$Week <-
  as.numeric(as.character(all.deaths.provis$Week))

cols1 <-c('#fdcc8a','#fc8d59','#e34a33','#b30000')
matplot(all.deaths.provis$epiwk ,all.deaths.provis[,c('2018-2019','2019-2020')], type='l', bty='l',col=cols1, main='Provisional deaths, reported in week 17', lty=1:4)
legend('bottomleft',legend=names(all.deaths.provis[,c('2018-2019','2019-2020')]),col=cols1, lty=1:4, ncol=2 )

diff <- all.deaths.provis$`2019-2020` -
  all.deaths.provis$`2018-2019`

all.deaths.provis.eval <-
  all.deaths.provis[all.deaths.provis$Week >=10 &
                      all.deaths.provis$Week<=15,]
eval.sum <- apply(all.deaths.provis.eval[,-c(1:3)],2,sum)
eval.sum['2019-2020'] - eval.sum['2018-2019']

```

```{r}
pneu.deaths.provis <-
  provis.data.c[provis.data.c$variable=='pi.deaths',]

matplot(pneu.deaths.provis$epiwk ,pneu.deaths.provis[,-c(1:3)], type='l', bty='l')
```

## Jags model
```{r}
#Ignore reports from first week
compare.m.alt <-   compare.m
#compare.m.alt <-
#  compare.m.alt[compare.m.alt$complete.weeks >=26,]


#Filter if death date hasn't happened yet or happened a week ago
compare.m.alt <-
  compare.m.alt[as.numeric((compare.m.alt$report_date - compare.m.alt$death_date)) > 6,]


#Split by state and death date
compare.m.alt.spl <- 
  split(compare.m.alt, paste0(compare.m.alt$state,compare.m.alt$death_date)) 

#Sort by report date
compare.m.alt.spl <- 
  lapply(compare.m.alt.spl, function(x) x[order(x$report_date),])

#Subtract previous value to calculate new value
compare.m.alt.spl <- lapply(compare.m.alt.spl, function(x){
  
  #Remove rdundant rows if deaths was >6 months ago
  if(max(x$complete.weeks)>=26){
    x <-   x[1,]
    x$complete.weeks <-999
  }
#Combine first and second weeks of observation
  x$complete.weeks[x$complete.weeks==1] <-2
  
  x$new.reports <- x$N_deaths

  if(nrow(x)>1){
    #If first observation we have for a week s after week 2, put in the 'most complete' column 999
    if(x$complete.weeks[1]>2){x$complete.weeks[1] <-999}
    
    for(i in 2:nrow(x)){
       x$new.reports[i]<-x$N_deaths[i]-x$N_deaths[(i-1)]
    }
  }
  return(x)
}) 

compare.m.alt.spl2 <-
  do.call(rbind.data.frame,compare.m.alt.spl)
#replace negative values with 0s
compare.m.alt.spl2$new.reports[compare.m.alt.spl2$new.reports<0] <-0

ds7 <- acast( compare.m.alt.spl2[,c('death_date','state','complete.weeks',"new.reports" )], state~ death_date ~ complete.weeks, value.var="new.reports" , fun.aggregate = sum)

ds7.length <- acast( compare.m.alt.spl2[,c('death_date','state','complete.weeks',"new.reports" )], state~ death_date ~ complete.weeks, value.var="new.reports" , fun.aggregate = length)

ds7[ds7.length==0] <-NA

compare.c.alt <- dcast( compare.m.alt.spl2[,c('death_date','state','complete.weeks',"new.reports" )], state+death_date + complete.weeks~., value.var="new.reports" , fun.aggregate = sum)
names(compare.c.alt) <-c('state', 'death_date','complete.weeks','new_reports')


```

```{r}
#reshaoe for INLA

d1 <- compare.c.alt[compare.c.alt$state=='Louisiana',]

```


## Param 1: model the new cases
```{r}
model_string_alt<-
"model
{
  # Likelihood
  for( t in 1:n.dates ){

  for(d in 1:(D+1)){
    n[t,d] ~ dpois(lambda[t,d] )
  
  log(lambda[t,d]) <- (int + beta.logged2[d] +
                    sin26[t]*delta[1] +
                    cos26[t]*delta[2] +
                    sin52[t]*delta[3] +
                    cos52[t]*delta[4] +
                    alpha[t] + 
                    phi[t]
                    ) 
  }
    sum.n[t] <- sum(n[t,])
  sum.lambda[t] <- sum(lambda[t,])
  }
  
  # Prior for alpha
  alpha[1] <-0
  phi[1] <-0
  for( t in 2:n.dates ){
  alpha[t] ~ dnorm(alpha[t-1],alphatau.prec.prior)
  phi[t] ~ dnorm(0, tau.disp)

  }

   ##  
  int~dnorm(0, 1e-4)

  ## Prior for beta
  beta.logged <- log(beta)
  beta.logged2 <- c(beta.logged,0)
  beta ~ ddirch(beta.priors)
  
  tau.disp<- 1/sd.disp^2
  sd.disp~dunif(0,100)
  
  # Prior for variance
  alpha1.prec.prior<- 1/alpha1.sd.prior^2
  alpha1.sd.prior~dunif(0,100)
  
  alphatau.prec.prior<- 1/alphatau.sd.prior^2
  alphatau.sd.prior~dunif(0,100)
  
  for(i in 1:4){
    delta[i] ~ dnorm(0,1e-4)
  }
}
"


```

```{r}

st1 <- ds7['Louisiana',,]
date.sum <- apply(st1,1,sum, na.rm=T) #total observations for 
death_date <- as.Date(dimnames(st1)[[1]])

st2 <- st1[, -ncol(st1)] #remove column '99'
week.index <- as.numeric(difftime(death_date, min(death_date), units='week'))
sin52 <- sin(2*pi*week.index/52.1775)
cos52 <- cos(2*pi*week.index/52.1775)

sin26 <- sin(2*pi*week.index*2/52.1775)
cos26 <- cos(2*pi*week.index*2/52.1775)

beta.priors <- rep(0.1, times=(ncol(st2)))

reporting.triangle <- st1

reporting.triangle[reporting.triangle[,1]>0, ncol(reporting.triangle)] <-NA

max_D <- ncol(reporting.triangle)-1


library(rjags)
library(HDInterval)
##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')

##############################################
#Model Organization
##############################################
model_spec<-textConnection(model_string_alt)
model_jags<-jags.model(model_spec, 
                       inits=list(inits1,inits2, inits3),
                       data=list('n.dates' =
                                   nrow(reporting.triangle),
                                 'n' = reporting.triangle,
                                 'D' = ncol(reporting.triangle)-1,
                                 'sin52'=sin52,
                                 'sin26'=sin26,
                                 'cos52'=cos52,
                                 'cos26'=cos26,
                           'beta.priors'=beta.priors
                                 
                                 ),
                       n.adapt=10000, 
                       n.chains=3)

params<-c('sum.n','sum.lambda',
          'phi','beta.logged')

##############################################
#Posterior Sampling
##############################################
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=5000)
posterior_samples.all<-do.call(rbind,posterior_samples)
#post1.summary<-summary(posterior_samples)
#post_means<-colMeans(posterior_samples.all)
post_means<-apply(posterior_samples.all, 2, median)
sample.labs<-names(post_means)
ci<-t(hdi(posterior_samples.all, credMass = 0.95))
ci<-matrix(sprintf("%.1f",round(ci,1)), ncol=2)
row.names(ci)<-sample.labs
post_means<-sprintf("%.1f",round(post_means,1))
names(post_means)<-sample.labs

pred.index <- grep('sum.n',sample.labs)
beta.index <- grep('beta.logged',sample.labs)

pred.means <- post_means[pred.index]
beta.log.means <- as.numeric(post_means[beta.index])
probs <- exp(beta.log.means)

pred.ci <- ci[pred.index,]
all.preds<- cbind(pred.means, pred.ci)
matplot(all.preds[,], type='l', lty=c(1,2,2), col=c('black','gray','gray'))
points(date.sum[]*2, type='p',pch=16 ,col='red')
```

#US national data
```{r}

```

