---
title: "us P&I mortality"
author: "Dan Weinberger"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE, echo=F}
knitr::opts_chunk$set(echo = FALSE)
library(reshape2)
library(ggplot2)
library(RColorBrewer)
library(plotly)
```

```{r}
## Install package
if (!require("devtools")) {
  install.packages("devtools")
}
#devtools::install_github("weinbergerlab/ExcessILI")
```

```{r}
library(ExcessILI)
library(cdcfluview)
```


```{r}
## Download the mortality data

pi.data <- pi_mortality(coverage_area='state')

```

```{r}
#Format and fill mssings with 0s

pi.data$state <- state.abb[match(pi.data$region_name, state.name)]
pi.data$state[pi.data$region_name == 'New York City'] <- 'NYC'
spl1<-split(pi.data, pi.data$state)
min.state <- lapply(spl1, function(x){ x$miss.x<-min(x$total_pni)
return(x)
                })
pi.data.clean <- do.call('rbind.data.frame',min.state)
pi.data.clean <- pi.data.clean[!is.na(pi.data.clean$miss.x),]
```

```{r}
#Run analysis
excess_deaths1.adjusted <-
  excessCases(ds = pi.data.clean,
              datevar       = "wk_start",
              statevar      = "state",
              denom.var     = "all_deaths",
              adj.flu       = "none",
              use.syndromes = c("total_pni"),
              extrapolation.date = "2020-03-01",
              time.res='week')
```


```{r, echo=F}
 #dashboardPlot(excess_deaths1.adjusted)
```


## Plot observed weekly death rate vs baseline


```{r}
### Extract the quantities of interest

#Which syndrome do you want to plot, and over what time range?

syndrome.select <- 'total_pni' #which syndrome do you want to plot?
n.days<-52  #How many days to plot?
ds <- excess_deaths1.adjusted
```
 
```{r}
#Extract the data needed to plot from the results

dates1 <-
  ds[[1]][[1]][[1]]$date
  
unexplained.cases <-
  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "unexplained.cases")

unexplained.log.rr <-
  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "resid1")

denom <-
  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "denom")


upi <-
  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "upi")

lpi <-
  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "lpi")

obs <-
  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "y")

pred<-  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "pred")

rr <-  excessExtract(ds = ds,
                syndrome = syndrome.select,
                extract.quantity = "resid1")
```

Generate the plots

```{r}
n.days <- 52
select.indices <- (length(dates1)-n.days):length(dates1)
dates<-dates1[select.indices]
states <- dimnames(pred)[[2]]
ages <- dimnames(pred)[[3]]
```


```{r, fig.width=8, fig.height=7}

  par(mfrow=c(4,4))

for(i in 1:dim(pred)[2]){
  for(j in 1:dim(pred)[3]){
    y.range1<-range(c( pred[select.indices,i,j]/denom[select.indices,i,j],obs[select.indices,i,j]/denom[select.indices,i,j], upi[select.indices,i,j]/denom[select.indices,i,j],0))
  plot(dates,
       pred[select.indices,i,j]/denom[select.indices,i,j],
       type='l',
       col='red',
       ylim=y.range1,
       bty='l',
       ylab='Proportion',
       main=paste(states[i],ages[j]))

  points(dates,
         obs[select.indices,i,j]/denom[select.indices,i,j],
         type='l',
         col='black')

  polygon(c(dates,
            rev(dates)),
          c(lpi[select.indices,i,j]/denom[select.indices,i,j],
            rev(upi[select.indices,i,j]/denom[select.indices,i,j])),
          col = rgb(1, 0, 0, alpha = 0.1),
          border = NA)
  }
}
```
## Observed/expected
```{r}
n.cols=100
set.seed(123)
rr2 <- as.data.frame(rr[select.indices,,1])
rr2$date <-dates
nice.cols <-  colorRampPalette(brewer.pal(11, "Set3"))(ncol(rr2))
nice.cols<-sample(nice.cols)

meltdf <- melt(rr2, id.vars = 'date')
meltdf$rr<-exp(meltdf$value)
p1<-ggplot(meltdf,aes(x=date,y=rr,
                      color=variable,
                      group=variable)) +
 geom_line() +  
  theme_bw() + 
  ggtitle("Excess P&I mortality") +
   labs(y="Observed/Expected")+
  theme(panel.border = element_blank()) + scale_color_manual(values = nice.cols)+
  scale_x_date(date_labels = "%b-%Y")
ggplotly(p1)
```